services:
  - type: web
    name: braille-server
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y tesseract-ocr

    startCommand: python app.py