services:
  - type: web
    name: braille-server
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: gunicorn app:app